/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_SAR_1.h"
#include "SIN_1_aliases.h"
#include "SIN_1.h"
#include "SIN_2_aliases.h"
#include "SIN_2.h"
#include "AMux_1.h"
#include "SIN_3_aliases.h"
#include "SIN_3.h"
#include "UART_PC.h"
#include "isr_PC.h"
#include "isr_ADC.h"
#include "Clock_1.h"
#include "timer_clock.h"
#include "Timer_1.h"
#include "isr_S1.h"
#include "timer_clock_1.h"
#include "Timer_2.h"
#include "isr_S2.h"
#include "ADC_SAR_1_IRQ.h"
#include "UART_PC_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

